import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={`${inter.className} flex flex-col lg:flex-row`}>
        <Header />

        <main className="flex h-fit min-h-screen w-full flex-col justify-between p-8 lg:max-w-[42rem]">
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
